from .clinical_support import CLINICAL_SUPPORT_DOMAIN
from .insurance_authorization import INSURANCE_AUTHORIZATION_DOMAIN
from .patient_intake import PATIENT_INTAKE_DOMAIN

HEALTHCARE_DOMAINS = [
    PATIENT_INTAKE_DOMAIN,
    INSURANCE_AUTHORIZATION_DOMAIN,
    CLINICAL_SUPPORT_DOMAIN,
]
